name: oltpb
favicon: null
layout_spectrum: 0
typography_spectrum: 0.32085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#b4b4b4'
    - '#c6e7cf'
    - '#337329'
    - '#957d25'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
