name: oltpb
favicon: null
layout_spectrum: 0.65833
typography_spectrum: 0.32085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#1b1924'
    - '#ce9785'
    - '#403e4c'
    - '#815853'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
