name: oltpb
favicon: null
layout_spectrum: 0.48517
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#1b1924'
    - '#ce9785'
    - '#403e4c'
    - '#815853'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
