name: oltpb
favicon: null
layout_spectrum: 0.60075
typography_spectrum: 0.26358305173926055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#b4b4b4'
    - '#c6e7cf'
    - '#337329'
    - '#957d25'
  brandStrength: 0.6875
  lightness: 0.10051063937135041
  saturation: 0.7671643840149045
  rhythmicContrast: 0.17602873593568802
purpose: []
