name: oltpb
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2555cf'
    - '#6e94e3'
    - '#87a7e5'
    - '#c6d7f4'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
